### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by aoamusat** [dev-haykay/MVCBoilerplate#2]
Please write more documentations about the usage.

**Comment by flaredragon** [comment]
@dev-haykay can I work on this? 
Secondly, Should I make a separate file or Update the Readme?

**Comment by aoamusat** [comment]
Update the readme.md file

**Comment by the7th** [comment]
Let's see if I can work on this out...

**Comment by aoamusat** [comment]
OK. Mr. Rahman. Fork the repo, commit your changes, make a PR and let see.
Thanks

**Comment by flaredragon** [comment]
@dev-haykay I made a PR :+1:

**Comment by aoamusat** [comment]
@the7th waiting for your PR
