### ISSUE TITLE
Error when trying to run this app.

### ISSUE THREAD

**Issue by the7th** [dev-haykay/MVCBoilerplate#7]
Catchable fatal error: Argument 1 passed to App::bind() must be an instance of string, string given, called in /Applications/MAMP/htdocs/MVCBoilerplate/app/core/bootstrap.php on line 3 and defined in /Applications/MAMP/htdocs/MVCBoilerplate/app/core/App.php on line 14

I am using the exact step as my pull request. Any clue as to why this is happening and how to fix it?

**Comment by the7th** [comment]
Oh I see... need to make the app to be on PHP7 or above. I am using PHP5.6 on my MAMP. I'll put it in the README file.

**Comment by aoamusat** [comment]
@the7th 
Can you work on how the config.php file works. Like explain what it does. 
Basically, this is where you configure your application database.

**Comment by thepassenger-hub** [comment]
Hi, I added description for the conf file but I couldn't find anywhere a sample of how you comment and describe functionalities so I kinda followed the laravel framework style and tried to make the comment as clear as possible.

**Comment by aoamusat** [comment]
OK. Make pr
